### ISSUE TITLE
Fails with puppetlabs/concat 4.1.1

### ISSUE THREAD

**Issue by bootc** [theforeman/puppet-dns#107]
When using `theforeman/dns` 5.1.0 with `puppetlabs/concat` 4.1.1, my catalogues fail to compile with the following error:

```
no parameter named 'format' at [...]/modules/concat/manifests/init.pp:94 on Concat_file[/etc/bind/zones.conf] at [...]/modules/concat/manifests/init.pp:94 on node foo.example.com
```

**Comment by ekohl** [comment]
We don't use this parameter but I've heard about similar issues with use in multiple environments. Do you happen to have one environment with an older concat? Generating puppet types could help.

**Comment by mmoll** [comment]
@bootc what's the status here?

**Comment by bootc** [comment]
Sorry, I haven't tried it again since I posted the issue, but I don't have any other environments at all. I _haven't_ tried restarting the puppetserver after updating the module, though, which I was going to try.

**Comment by bootc** [comment]
Yes, it looks like restarting the puppetserver instance altogether fixed it.

**Comment by mmoll** [comment]
Thanks, then it's a known problem with puppetserver, which is internally not updating some of the ruby code brought in by modules, when the files change.
