### ISSUE TITLE
Add package_ensure parameter

### ISSUE THREAD

**Issue by serverbiz** [theforeman/puppet-dns#113]
init.pp has service_ensure and service_enable, but no package_ensure. install.pp thus always ensures the package is present. There is no way to use this module without having it install the package, or to enforce the installed version (like latest).

This would be a useful feature, like in our case where we want to use puppet to create the configuration, but don't want it installed because we want to run bind in a Docker container.

**Comment by mmoll** [comment]
pull requests welcome :)

**Comment by ekohl** [comment]
This can be achieved as well by passing an empty string to the `dns_server_package` parameter. Patch is still welcome because users might want to ensure latest.

**Comment by ekohl** [comment]
Closing since it's open for a while and there's a workaround. A PR is still welcome.
