### ISSUE TITLE
Missing zone options

### ISSUE THREAD

**Issue by damluk** [theforeman/puppet-dns#156]
I would like to set several options inside zones that are currenty not supported by `named.zone.erb`. Would you like to make me a merge request with a bunch of new `dns::zone` parameters or with an `additional_options` parameter?

**Comment by ekohl** [comment]
A PR with that would be welcome. It depends on the number of options and how well defined they are, but I think a bunch of parameters is where I'd start.

**Comment by damluk** [comment]
A zone definition supports ~75 different parameters. Do I need to be exhaustive in the PR? I am currently only interested in about five of them.

**Comment by ekohl** [comment]
No need for an exhaustive list, just the ones you care about. It's how I always do PRs :)

**Comment by ekohl** [comment]
With both PRs merged, is there still something to do here?

**Comment by damluk** [comment]
> With both PRs merged, is there still something to do here?

Nope, we are done, thanks. :)
