### ISSUE TITLE
Manage zone records

### ISSUE THREAD

**Issue by BDelacour** [theforeman/puppet-dns#196]
Hello,

Is there a way to manage zones records ?
I would like Puppet to enforce my complete bind configuration.

Actually, `zone.header.erb` only manages the header of the file.
Is there a way without concat to add my records (A, CNAME, ...) at the bottom ?

Thank you !

**Comment by ekohl** [comment]
Today it's not easy. You can set `manage_file` to false and manually manage it.

This is mostly because in our use case we allow updates via `nsupdate`. Since it's all dynamic at runtime, the file must not be overwritten. This is a slightly different model than where Puppet is fully in control.

**Comment by rtprio** [comment]
Is this a feature that you'd be receptive to merging, even if it's a feature you wouldn't be using?

Other modules do this, but don't have such broad support (like FreeBSD).

**Comment by ekohl** [comment]
I would be. As long as it's clear and works consistently. Ideally speaking it would even disallow nsupdate commands to zones that are managed by Puppet to avoid nasty situations where Puppet reverts changes, but I'd be happy with a clear note (either in readme or in class/definition documentation that you should be aware of this.

**Comment by rtprio** [comment]
Seems more cluttered when I try to do it this way, and it changes the zone file resource into a concat resource. Which I guess isn't a problem but complicates both the code and the tests.
