### ISSUE TITLE
dnssec-enable no longer a valid configuration item.

### ISSUE THREAD

**Issue by HugoNikanor** [theforeman/puppet-dns#207]
Since bind 9.18 a number of deprecated options were removed, and are errors to include in the configuration https://bind9.readthedocs.io/en/v9_18_0/notes.html

**Comment by ekohl** [comment]
Looks like Arch is hitting this as well (https://github.com/theforeman/puppet-dns/runs/5482656027?check_suite_focus=true). Any idea about a patch to solve it?

**Comment by ekohl** [comment]
Could you have a look at https://github.com/theforeman/puppet-dns/pull/210 and see what you think?
