### ISSUE TITLE
defaultzonepath parameter defined, but not used in template name.conf.erb

### ISSUE THREAD

**Issue by benjamin-robertson** [theforeman/puppet-dns#216]
dns::defaultzonepath is defined as a parameter, however setting this has no effect to named.conf.

**Comment by ekohl** [comment]
I'm not entirely sure that's correct. It is used here:
https://github.com/theforeman/puppet-dns/blob/47fb22b2812302167b0003bc1479346ffa3b199c/templates/named.view_header.erb#L50-L54

**Comment by benjamin-robertson** [comment]
Yes true, it is used as part of views configuration. But it should also be used as a global setting under named.conf.
