### ISSUE TITLE
sysconfig_file for Debian and Ubuntu is wrong and has long changed to /etc/default/named

### ISSUE THREAD

**Issue by frittentheke** [theforeman/puppet-dns#234]
Currently this module still writes to `/etc/default/bind9`, but since Debian Bullseye and at least Ubuntu Focal (20.04) the defaults was renamed to `/etc/default/named`.

See https://salsa.debian.org/dns-team/bind9/-/blob/debian/9.18/debian/bind9.named.service#L10
unfortunately there was never a note in the release notes (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23993257), but still the current value is wrong.``

**Comment by ekohl** [comment]
Thanks for pointing this out. Could you come up with a PR to resolve this?
