### ISSUE TITLE
Please update the named.ca file

### ISSUE THREAD

**Issue by bigon** [theforeman/puppet-dns#256]
Hello,

The root DNS file currently in the git repository is from 2008 (Feb 04, 2008)

The current one on internic is from June 26, 2024

I guess it should be updated

https://www.internic.net/domain/named.root

**Comment by ekohl** [comment]
As mentioned in https://github.com/theforeman/puppet-dns/pull/257#pullrequestreview-2144972868, it's no longer used and should be removed.
