### ISSUE TITLE
zones.conf missing when chroot enabled

### ISSUE THREAD

**Issue by treydock** [theforeman/puppet-dns#58]
The EL6 `/etc/sysconfig/named` documents a list of files and directories that are mounted into named chroot when `ROOTDIR` is set.  The `/etc/zones.conf` file is not in the list, my guess is the location is not what bind expects.  I can submit a PR that modifies the path of `zones.conf` to be `/etc/named/zones.conf`, but wanted to get an idea if such a change would be accepted.

**Comment by domcleal** [comment]
Sounds OK to me, I think.

**Comment by mmoll** [comment]
should be fixed with #59
