### ISSUE TITLE
DNS class written by theforeman doesn't allow editing zones in theforeman

### ISSUE THREAD

**Issue by pauldsmyth** [theforeman/puppet-dns#62]
Having installed this module I find that it's not possible to edit the zone parameter. Some classes need some manual editing to work "theforeman" way but I would've expected a class written by you guys to work "out of the box". I'd appreciate a little guidance as your documentation is virtually non-existent

**Comment by ekohl** [comment]
> Having installed this module I find that it's not possible to edit the zone parameter. Some classes need some manual editing to work "theforeman" way but I would've expected a class written by you guys to work "out of the box".

Inside the foreman installer we use this module through the [puppet-foreman_proxy::proxydns class](https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/proxydns.pp). Could you describe manual editing you need to do?

> I'd appreciate a little guidance as your documentation is virtually non-existent

Our documentation is limited to put it mildly. Any particular use cases you would like to see described?

**Comment by pauldsmyth** [comment]
Hi Ewoud,

My aim is to reach a point where servers can be configured and maintained
without logging in to the console directly. I would like to be able to
maintain DHCP & DNS without having to edit files directly. Just the basics
really, manually add a host to DNS, make DHCP configuration changes etc. If
I'm barking up the wrong tree here perhaps I have to write my own module.

Thanks

Paul

**Comment by ekohl** [comment]
That should be possible. The foreman does this through the foreman smart proxy which can talk to DHCP & DNS. By default this module sets up zones so you can edit them using nsupdate which foreman-proxy does for you. Then foreman talks to foreman-proxy when you create a host. The same can be done for DHCP.

In short: I'd start with looking at puppet-foreman_proxy, set ```dns``` and ```dhcp``` to true. That should set you up with a working proxy. You should look at the domain it creates (the ```dns_zone``` parameter), ensure it also exists in the foreman and linked to the proper proxy. For DHCP there are similar options to create the correct subnet.

Once you have multiple zones/subnets, our default module config is lacking but you can use ```dns::zone``` and ```dhcp::pool``` to create additional ones.

**Comment by pauldsmyth** [comment]
Thanks Ewoud, I'll see how I go on and fire back some documentation once I
have success :-)

**Comment by ekohl** [comment]
Pease do feel free to ask questions. What you want sounds like the default foreman setup so it should be properly supported (and documented).

**Comment by pauldsmyth** [comment]
Thanks, I do appreciate that this is a give and take process so if I can
contribute anything meaningful back I'll certainly do that. This is my
development system at home I'm testing on and yes, it's a default Foreman
install only a week old.

**Comment by mmoll** [comment]
@pauldsmyth what's the status here?

**Comment by pauldsmyth** [comment]
Sorry for the late response, I have no idea, I'm just another user. I don't have time to delve into the code if something doesn't work I just find another way to achieve my aim which is what I've done for now.

**Comment by mmoll** [comment]
ok, thanks!
