### ISSUE TITLE
Minor glitch in README

### ISSUE THREAD

**Issue by hguemar** [theforeman/puppet-dns#66]
README says that this project is licensed under GPLv3+ but LICENSE and metadata says ASL 2.0, could you fix it, please?

**Comment by mmoll** [comment]
@GregSutcliffe as you did the inital fork and import, could you have a look?

**Comment by GregSutcliffe** [comment]
The original module was from Zach Leslie, IIRC, but it seems to be gone from his GitHub repos now. Assuming that's now https://github.com/xaque208/puppetlabs-dns then the original appears to be Apache 2.0 - but that module doesn't support Bind, so maybe that's not it.

So, perhaps the best thing to do is ask :)

@xaque208 This is going back to 2012 but do you happen to recall the license for your old DNS module? Or, to ask a different question, do you have any concerns about clarifying the license on this derivative module?

**Comment by GregSutcliffe** [comment]
@xaque208 scratch that, the history has been traced - ty anyway!

**Comment by xaque208** [comment]
Oh gad!  I don't think the bind module ever made it public, though it should have.  Glad you sorted it out, as that was ages ago.  All licensing for PuppetLabs items should be Apache2.  Cheers @GregSutcliffe.
