### ISSUE TITLE
Make zone template configurable

### ISSUE THREAD

**Issue by not-known** [theforeman/puppet-dns#90]
Is it possible to make the location of the named.zone.erb template configurable like the other templates? This way i can manage the base zone settings from a custom template and keep the config clean.

**Comment by ekohl** [comment]
I think we could make the template name a parameter. Is there anything you're missing from our current options?

**Comment by not-known** [comment]
Well I need a custom update-policy so I can manage multiple keys that can update my zones dynamically. In the current situation there is only one static update-policy available and I need to override this to make my setup work. It is possible to make it a build-in feature, but there are situations where a full template replacement might be easier.

**Comment by ekohl** [comment]
Apologies for the slow reply. If it's just one parameter then for now I'd prefer to only add that because we're much less likely to accidentally break something for users. Could you come up with a PR?

**Comment by ekohl** [comment]
I'm going to close this due to its age and a lack of activity. It's possible not to manage the file in the module and manually do this if needed so there is a workaround.
