### ISSUE TITLE
Add support for adding keys for nsupdate

### ISSUE THREAD

**Issue by mstinsky** [theforeman/puppet-dns#94]
Hey,

I am in the middle of evaluating a foreman puppet setup, trying out all the foreman smart proxy features. I want to do everything through puppet and u guys have pretty good modules already for that. But i can't find how I would be able to add a key to bind for foremans nsupdates, shoulnd this be supported by this module or am I missing something ?

Best regards

**Comment by ekohl** [comment]
That's a good question I didn't really consider. When I still used bind + dhcpd the services were on the same machine so limiting to localhost was sufficient for me. It looks like this is only doable with custom includes and not trivial out of the box.

Pull requests are highly appreciated but a description of what you'd expect is also very useful.

**Comment by mstinsky** [comment]
I will look into if i can make a pull request happen for that.
What i expect as a minimum for this is to do the exact steps that are pointed out in the Foreman Manual (4.3.5.2 BIND):

1. Add a key to the named.conf.
2. Add update-policy for that key to specified zone.
Optional but would be a big plus: Create the key through this module.

**Comment by ekohl** [comment]
Let me know if you want help. Also very early work in progress reviews are not a problem.
